import { Html, Text } from "@react-three/drei";
import { fadeOnBeforeCompileFlat } from "./utils/fadeMaterial";
export const TextSection = ({
  Megatitle,
  title,
  subtitle,
  skilltitle,
  langtitle,
  libtitle,
  works,
  subworks,
  ...props
}) => {
  return (
    <group {...props}>
      {!!Megatitle && (
        <Text
          color="white"
          anchorX={"left"}
          anchorY="middle"
          fontSize={0.52}
          maxWith={2.5}
          position-x={-0.5}
          position-y={1.0}
          font={"./fonts/DMSerifDisplay-Regular.ttf"}
          onBeforeCompile={fadeOnBeforeCompileFlat}
        >
          {Megatitle}
          <meshStandardMaterial
            color={"white"}
            onBeforeCompile={fadeOnBeforeCompileFlat}
          />
        </Text>
      )}
      {!!title && (
        <Text
          color="white"
          anchorX={"left"}
          anchorY="buttom"
          position-x={0}
          position-y={0.7}
          fontSize={0.52}
          maxWith={2.5}
          lineHeight={1}
          font={"./fonts/LibreCaslonText-Regular.ttf"}
        >
          {title}
          <meshStandardMaterial
            color={"white"}
            onBeforeCompile={fadeOnBeforeCompileFlat}
          />
        </Text>
      )}
      {!!subtitle && (
        <Text
          color="white"
          anchorX={"left"}
          anchorY="top"
          position-y={0.2}
          fontSize={0.23}
          position-x={-0.5}
          maxWidth={4}
          textAlign="justify"
          font={"./fonts/Inter-Regular.ttf"}
        >
          {subtitle}
          <meshStandardMaterial
            color={"white"}
            onBeforeCompile={fadeOnBeforeCompileFlat}
          />
        </Text>
      )}
      {!!skilltitle && (
        <Text
          color="white"
          anchorX={"left"}
          anchorY="buttom"
          position-x={0}
          position-y={0.9}
          fontSize={0.52}
          maxWith={2.5}
          lineHeight={1}
          font={"./fonts/LibreCaslonText-Regular.ttf"}
        >
          {skilltitle}
          <meshStandardMaterial
            color={"white"}
            onBeforeCompile={fadeOnBeforeCompileFlat}
          />
        </Text>
      )}
      {!!langtitle && (
        <Text
          color="white"
          anchorX={"left"}
          anchorY="buttom"
          position-x={-0.9}
          position-y={0.2}
          fontSize={0.23}
          maxWith={2.5}
          lineHeight={1}
          font={"./fonts/Inter-Regular.ttf"}
        >
          {langtitle}
          <meshStandardMaterial
            color={"white"}
            onBeforeCompile={fadeOnBeforeCompileFlat}
          />
        </Text>
      )}
      {!!libtitle && (
        <Text
          color="white"
          anchorX={"left"}
          anchorY="buttom"
          position-x={-0.9}
          position-y={-1}
          fontSize={0.23}
          maxWith={2.5}
          lineHeight={1}
          font={"./fonts/Inter-Regular.ttf"}
        >
          {libtitle}
          <meshStandardMaterial
            color={"white"}
            onBeforeCompile={fadeOnBeforeCompileFlat}
          />
        </Text>
      )}
      {!!works && (
        <Text
          color="white"
          anchorX={"left"}
          anchorY="buttom"
          position-x={0.4}
          position-y={1}
          fontSize={0.52}
          maxWith={2.5}
          lineHeight={1}
          font={"./fonts/LibreCaslonText-Regular.ttf"}
        >
          {works}
          <meshStandardMaterial
            color={"white"}
            onBeforeCompile={fadeOnBeforeCompileFlat}
          />
        </Text>
      )}
      {!!subworks && (
        <Text
          lineHeight={1.5}
          color="white"
          anchorX={"left"}
          anchorY="top"
          position-y={0.6}
          fontSize={0.23}
          position-x={-0.5}
          maxWidth={4}
          textAlign="justify"
          font={"./fonts/Inter-Regular.ttf"}
        >
          {subworks}
          <meshStandardMaterial
            color={"white"}
            onBeforeCompile={fadeOnBeforeCompileFlat}
          />
        </Text>
      )}
    </group>
  );
};
